export const GET_EMPLOYEES = "GET_EMPLOYEES";
export const ADD_EMPLOYEE = "ADD_EMPLOYEE";
export const DEL_EMPLOYEE = "DEL_EMPLOYEE";
export const EMPLOYEES_LOADING = "EMPLOYEES_LOADING";
export const UPDATE_SUCCES = "UPDATE_SUCCES";
export const UPDATE_FAIL = "UPDATE_FAIL";
